/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_propeller_preprocessing_VideoPreProcessing */

#ifndef _Included_io_agora_propeller_preprocessing_VideoPreProcessing
#define _Included_io_agora_propeller_preprocessing_VideoPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_agora_propeller_preprocessing_VideoPreProcessing
 * Method:    enablePreProcessing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_agora_propeller_preprocessing_VideoPreProcessing_enablePreProcessing
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
