parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''
  sdkurl: ''

jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-10.14'

    variables:
      - group: AgoraKeys

    steps:
      - script: cd cicd/scripts && chmod +x sdkdownload.sh && ./sdkdownload.sh ${{ parameters.sdkurl }} ${{ parameters.workingDirectory}}/${{ parameters.scheme }} Static
    
      - script: echo `pwd` && cd ${{ parameters.workingDirectory }} && ls && python ci.env.py
        env:
          AGORA_APP_ID: $(agora.appId)
          SDK_URL: ${{ parameters.sdkurl }}

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'certificate.p12'
          certPwd: $(agora.password)

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provProfileSecureFile: 'AgoraAppsDevProfile.mobileprovision'

      - script: cd ${{ parameters.workingDirectory }} && chmod +x build.sh && ./build.sh

      - script: cd ${{ parameters.workingDirectory }} && mkdir app && mv *.ipa app && mv *.xcarchive app && zip -r ${{ parameters.displayName }}.zip app

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          ArtifactName: ${{ parameters.displayName }}

      - template: github-release.yml
        parameters:
          displayName: ${{ parameters.displayName }}
